<?php
/*
 * Test
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TestLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class BaseObject implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $uid public property
     */
    public $uid;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $uid Initialization value for $this->uid
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->uid = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['uid'] = $this->uid;

        return $json;
    }
}
