<?php
/*
 * Test
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TestLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class MyObject implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps @context
     * @var string $mContext public property
     */
    public $mContext;

    /**
     * @todo Write general description for this property
     * @required
     * @maps @id
     * @var string $mId public property
     */
    public $mId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $born public property
     */
    public $born;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $spouse public property
     */
    public $spouse;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $mContext Initialization value for $this->mContext
     * @param string $mId      Initialization value for $this->mId
     * @param string $name     Initialization value for $this->name
     * @param string $born     Initialization value for $this->born
     * @param string $spouse   Initialization value for $this->spouse
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->mContext = func_get_arg(0);
            $this->mId      = func_get_arg(1);
            $this->name     = func_get_arg(2);
            $this->born     = func_get_arg(3);
            $this->spouse   = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['@context'] = $this->mContext;
        $json['@id']      = $this->mId;
        $json['name']     = $this->name;
        $json['born']     = $this->born;
        $json['spouse']   = $this->spouse;

        return $json;
    }
}
