<?php
/*
 * Test
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TestLib\Models;

/**
 * Possible operators are sum, subtract, multiply, divide
 */
class OperationTypeEnum
{
    /**
     * Represents the sum operator
     */
    const SUM = "SUM";

    /**
     * Represents the subtract operator
     */
    const SUBTRACT = "SUBTRACT";

    /**
     * Represents the multiply operator
     */
    const MULTIPLY = "MULTIPLY";

    /**
     * Represents the divide operator
     */
    const DIVIDE = "DIVIDE";
}
