<?php
/*
 * Test
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TestLib;

use TestLib\Controllers;

/**
 * Test client class
 */
class TestClient
{
 
    /**
     * Singleton access to SimpleCalculator controller
     * @return Controllers\SimpleCalculatorController The *Singleton* instance
     */
    public function getSimpleCalculator()
    {
        return Controllers\SimpleCalculatorController::getInstance();
    }
}
